version: "3.8"
services:
# servicio de base de datos postgres utilizado como main data warehouse
  postgres:
    image: postgres:15
    container_name: worldbank_postgres

    # credenciales de base de datos en la variable de entorno
    env_file:
      - .env

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      # puerto para exponer postgres localmente
    ports:
      - "5432:5432"

      # ruta para base de datos y ejecutar scripts sql
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/scripts

      # comprobacion de estado para garantizar que postgres este listo ates que arranque el servicio
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5



# contenedor de inicializacion de airflow, prepara la base de datos y crea usuarios
  airflow-init:
    image: apache/airflow:2.9.3
    container_name: worldbank_airflow_init

    # espera que postgres este listo antes de iniciar airflow
    depends_on:
      postgres:
        condition: service_healthy

    # variables de entorno
    env_file:
      - .env

    # dependencias python 
    environment:
      _PIP_ADDITIONAL_REQUIREMENTS: pandas openpyxl
      PYTHONPATH: /opt/airflow

# rutas de codigo principal airflow, (dags, configuracion etc), scripts y sql utilizado por dags
    volumes:
      - ./airflow:/opt/airflow
      - ./scripts:/scripts
      - ./sql:/opt/airflow/sql
    entrypoint: /bin/bash

    # inicializa db de airflow y crea usuario admin
    command: >
      -c "airflow db init &&
        airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com"
    restart: "no"



# servicio para levantar interfaz airflow
  airflow-webserver:
    image: apache/airflow:2.9.3
    container_name: worldbank_airflow_webserver

    # solo inicia despues del servicio airflow-init
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      _PIP_ADDITIONAL_REQUIREMENTS: pandas openpyxl
      PYTHONPATH: /opt/airflow
    volumes:
      - ./airflow:/opt/airflow
      - ./sql:/opt/airflow/sql
      - ./airflow/dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts

    # exponemos la ui web en este puerto
    ports:
      - "8080:8080"
    command: webserver



# servicio responsable de ejecutar las tareas de los dags
  airflow-scheduler:
    image: apache/airflow:2.9.3
    container_name: worldbank_airflow_scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      _PIP_ADDITIONAL_REQUIREMENTS: pandas openpyxl
      PYTHONPATH: /opt/airflow
    volumes:
      - ./airflow:/opt/airflow
      - ./sql:/opt/airflow/sql
      - ./airflow/dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
    command: scheduler

# volumen persistente para almacenar los datos de postres, evita perdidas de datos al reiniciar contenedor
volumes:
  postgres_data:
